### PR TITLE
Clearing the Event Keydowns after a success match.

### PR DESCRIPTION
**Pull request by LeaveNhA**
I don't know if it brokes some of your (near) future plans on the business logic of the library, but this way, some real-time interactions are possible.

We are reading the pressed keys from the source without any runtime work-load since they are there for matching new events.

Sincerely.

### CODE REVIEW

**Comment by gadfly361** [comment]
@LeaveNhA Thanks for the contribution! I think this is an interesting idea to clear on match, however, it would be a breaking change. Can we avoid the breaking change by making the clear on match optional and default to not happen?

**Comment by LeaveNhA** [comment]
> @LeaveNhA Thanks for the contribution! I think this is an interesting idea to clear on match, however, it would be a breaking change. Can we avoid the breaking change by making the clear on match optional and default to not happen?

Of course! I already thought that it would be a breaking change but I couldn't resist.
I need to alter the logic again, for not recording any unmatched first/initial key presses.

Sincerely.

**Comment by LeaveNhA** [comment]
Hello, @gadfly361!

I think, this is an acceptable version of the idea and it carries zero breaking changes.
I tested it with my own environment but we need to implement our edge-case tests. I will work on that but not now, sorry.

Sincerely.

**Comment by gadfly361** [comment]
@LeaveNhA Thanks for this PR! I will need to test it locally before merging, but it looks good.

**Comment by gadfly361** [comment]
Just an update, I haven't forgotten about this PR, just haven't had much time lately, my apologies 🙏

**Comment by LeaveNhA** [comment]
Don't worry. We are waiting. 👴🏻

**Comment by gadfly361** [comment]
@LeaveNhA Can you remove the injection of `:keyboard` in the various db paths? I was intentionally using a leading keyword that was namespaced to avoid collisions in the db.

**Comment by LeaveNhA** [comment]
It's fine now. You can merge it @gadfly361.

**Review by gadfly361 — APPROVED** [review]
@LeaveNhA Thank you!

**Pull request merged**
